// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_ImobiliariaSantos.Models;

namespace WebAPI_ImobiliariaSantos.Migrations
{
    [DbContext(typeof(ContextoDataBase))]
    [Migration("20230224210118_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI_ImobiliariaSantos.Models.Imoveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricaoImovel")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("enderecoImovel")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("finalidadeImovel")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("imagemImovel")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<decimal>("precoImovel")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<string>("tipoImovel")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("imoveis");
                });

            modelBuilder.Entity("WebAPI_ImobiliariaSantos.Models.Locatarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cpfLocatario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dataLocLocatario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dataNascLocatario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dataVencimentoAlugLocatario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("imagemLocatario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("nomeLocatario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("locatarios");
                });
#pragma warning restore 612, 618
        }
    }
}
